/*
 * This source file was generated by the Gradle 'init' task
 */
package interpolation.client;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("Video Frame Rate Enhancer");
        Button btn = new Button();
        btn.setText("Click Here to Continue");

       
        
    
        btn.setOnAction(new EventHandler<ActionEvent>() {
 
            @Override
            public void handle(ActionEvent event) {

                Stage domain = new Stage();
                domain.setTitle("Enter Website URL");

                Button btn2 = new Button();
                btn2.setText("OK");

                TextField textField1 = new TextField();
                textField1.setPromptText("Enter something here...");
            

                VBox popupLayout = new VBox(10);  
                popupLayout.getChildren().addAll(textField1, btn2);

                // Set the scene and show the pop-up window
                Scene popupScene = new Scene(popupLayout, 250, 150);
                domain.setScene(popupScene);
                domain.show();

                btn2.setOnAction(new EventHandler<ActionEvent>() {
 
                    public void handle2(ActionEvent event) {
        
                        Stage domain2 = new Stage();
                        domain2.setTitle("");
        
                     

                        // Set the scene and show the pop-up window
                        Scene popupScene2 = new Scene(popupLayout, 250, 150);
                        domain2.setScene(popupScene2);
                        domain2.show();
        
        
                    }

                    @Override
                    public void handle(ActionEvent event) {
                        // TODO Auto-generated method stub
                        throw new UnsupportedOperationException("Unimplemented method 'handle'");
                    }
                });

            }
        });

       
        
        StackPane root = new StackPane();
        root.getChildren().add(btn);
        primaryStage.setScene(new Scene(root, 300, 250));
        primaryStage.show();
    }
}
