/*
 * This source file was generated by the Gradle 'init' task
 */
package interpolation.client;

import interpolation.client.video.VideoTransfer;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

import java.io.File;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Interpolation Client");

        // VideoTransfer instance
        VideoTransfer videoTransfer = new VideoTransfer("http://example.com");

        // Input field for URL
        Label urlLabel = new Label("Enter URL:");
        TextField urlField = new TextField();
        urlField.setPromptText("http://example.com");

        // File chooser for uploading a video
        Button chooseFileButton = new Button("Choose Video File");
        Label chosenFileLabel = new Label("No file selected");

        // Upload button
        Button uploadButton = new Button("Upload");
        Label statusLabel = new Label("Status: Waiting for input");
        Label downloadLabel = new Label();

        // File selection action
        FileChooser fileChooser = new FileChooser();
        final File[] selectedFile = {null};
        chooseFileButton.setOnAction(e -> {
            File file = fileChooser.showOpenDialog(primaryStage);
            if (file != null) {
                chosenFileLabel.setText("Selected: " + file.getName());
                selectedFile[0] = file;
            } else {
                chosenFileLabel.setText("No file selected");
            }
        });

        // Upload button action
        uploadButton.setOnAction(e -> {
            if (selectedFile[0] != null) {
                String url = urlField.getText();
                if (!url.isEmpty()) {
                    statusLabel.setText("Uploading to: " + url);
                    String downloadLink = videoTransfer.uploadVideo(selectedFile[0]); // Simulated upload
                    if (downloadLink != null) {
                        downloadLabel.setText("Download Link: " + downloadLink);
                    } else {
                        downloadLabel.setText("Error: Unable to generate download link");
                    }
                } else {
                    statusLabel.setText("Error: URL field is empty");
                }
            } else {
                statusLabel.setText("Error: No file selected");
            }
        });

        // Layout
        VBox root = new VBox(10);
        root.setPadding(new Insets(15));
        root.getChildren().addAll(urlLabel, urlField, chooseFileButton, chosenFileLabel, uploadButton, statusLabel, downloadLabel);

        // Set up the scene and stage
        primaryStage.setScene(new Scene(root, 400, 300));
        primaryStage.show();
    }
}
