/*
 * This source file was generated by the Gradle 'init' task
 */
package interpolation.client;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }
}
