spring:
  config:
    import:
      'file:./secrets.yml'
  application:
    name: datasetserver
  #datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: postgresql
    #database-platform: 'org.hibernate.dialect.PostgreSQL81Dialect'
server:
  port: 8080