spring:
  datasource:
    hikari:
      maximum-pool-size: 200
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      reWriteBatchedInserts: true
    url: 'jdbc:mysql://localhost:3306/tensor?useSSL=false&allowPublicKeyRetrieval=true'
    username: tensor
    password: DontTensorMyFriend
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 200
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: false
    hibernate:
      ddl-auto: create-drop
      jdbc:
        batch_size: 200
dataset:
  location:
    train: 'train_data/train'
    validate: 'train_data/validate'
    test: 'train_data/test'