spring:
  datasource:
    url: 'jdbc:sqlite:test.db'
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
dataset:
  location:
    train: 'train_data/train'
    validate: 'train_data/val'
    test: 'train_data/test'